"""empty message

Revision ID: 9f755c367f6d
Revises: None
Create Date: 2016-11-21 13:16:22.753496

"""

# revision identifiers, used by Alembic.
revision = '9f755c367f6d'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publisher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publisher_name'), 'publisher', ['name'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('email', sa.TEXT(), nullable=True),
    sa.Column('secret', sa.TEXT(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('full_name', sa.TEXT(), nullable=True),
    sa.Column('auth0_id', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_auth0_id'), 'user', ['auth0_id'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=True)
    op.create_table('package',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('descriptor', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.TEXT(), nullable=True),
    sa.Column('private', sa.Boolean(), nullable=True),
    sa.Column('readme', sa.TEXT(), nullable=True),
    sa.Column('publisher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['publisher_id'], [u'publisher.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'publisher_id')
    )
    op.create_index(op.f('ix_package_name'), 'package', ['name'], unique=False)
    op.create_index(op.f('ix_package_status'), 'package', ['status'], unique=False)
    op.create_table('publisher_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('publisher_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['publisher_id'], [u'publisher.id'], ),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], ),
    sa.PrimaryKeyConstraint('id', 'user_id', 'publisher_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('publisher_user')
    op.drop_index(op.f('ix_package_status'), table_name='package')
    op.drop_index(op.f('ix_package_name'), table_name='package')
    op.drop_table('package')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_auth0_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_publisher_name'), table_name='publisher')
    op.drop_table('publisher')
    ### end Alembic commands ###
